// MBTI Test Data - 93 Questions with Likert Scale
// 5-level: 非常像A(+2), 比较像A(+1), 居中(0), 比较像B(-1), 非常像B(-2)

var MBTI_DATA = {
    questions: [
        // ===== Section 1: 1-42题 =====
        { id: 1, dimension: "EI", question: "电话铃声突然响起或类似这样的突发性事件，你习惯最先做出回应", phraseLeft: "是的", phraseRight: "不会", leftLetter: "E", rightLetter: "I" },
        { id: 2, dimension: "SN", question: "热衷于猎奇和掌握新概念", phraseLeft: "是的", phraseRight: "不会", leftLetter: "N", rightLetter: "S" },
        { id: 3, dimension: "TF", question: "你看肥皂剧的时候会很投入", phraseLeft: "是的", phraseRight: "不会", leftLetter: "F", rightLetter: "T" },
        { id: 4, dimension: "EI", question: "你乐于拥有广泛的人际圈", phraseLeft: "是的", phraseRight: "如果可以选择的话，我更愿意一个人静静呆着", leftLetter: "E", rightLetter: "I" },
        { id: 5, dimension: "JP", question: "你有时候会心血来潮做一件事情", phraseLeft: "是的", phraseRight: "极少会这样", leftLetter: "P", rightLetter: "J" },
        { id: 6, dimension: "EI", question: "业余时间里你常与一群人积极交往，参加聚会、一起购物", phraseLeft: "是的", phraseRight: "不，我独自呆着比较舒服", leftLetter: "E", rightLetter: "I" },
        { id: 7, dimension: "JP", question: "你喜欢立刻行动而不习惯对各种选择进行反复斟酌", phraseLeft: "是的", phraseRight: "不是", leftLetter: "P", rightLetter: "J" },
        { id: 8, dimension: "SN", question: "你经常考虑人类及其命运问题", phraseLeft: "是的", phraseRight: "不会", leftLetter: "N", rightLetter: "S" },
        { id: 9, dimension: "JP", question: "你懂得如何把每分每秒都花得有意义", phraseLeft: "是的", phraseRight: "不习惯计划时间，喜欢随心所欲", leftLetter: "J", rightLetter: "P" },
        { id: 10, dimension: "EI", question: "总体而言，你是一个在交流时有些保守和有距离感的人", phraseLeft: "是的", phraseRight: "不是", leftLetter: "I", rightLetter: "E" },
        { id: 11, dimension: "TF", question: "你时常容易流露和说出你的感觉和感情", phraseLeft: "是的", phraseRight: "不易流露感情", leftLetter: "F", rightLetter: "T" },
        { id: 12, dimension: "TF", question: "你常会站在对方角度去思考而模糊了自己的立场", phraseLeft: "是的", phraseRight: "不会", leftLetter: "F", rightLetter: "T" },
        { id: 13, dimension: "SN", question: "你容易看出具体事件背后的普遍原理", phraseLeft: "是的", phraseRight: "不是", leftLetter: "N", rightLetter: "S" },
        { id: 14, dimension: "EI", question: "大多数时候，你宁可看一本书，也不愿意出去参加聚会", phraseLeft: "是的", phraseRight: "我喜欢参加聚会", leftLetter: "I", rightLetter: "E" },
        { id: 15, dimension: "TF", question: "你常看到感人的电视或电影情景看到泪流不止", phraseLeft: "是的", phraseRight: "我很少因为这样的事情哭，只有特别伤心的事发生在自己身上时才会哭", leftLetter: "F", rightLetter: "T" },
        { id: 16, dimension: "EI", question: "你更喜欢远离外界的喧嚣", phraseLeft: "是的", phraseRight: "不是，我喜欢热闹", leftLetter: "I", rightLetter: "E" },
        { id: 17, dimension: "JP", question: "你是一个时间观念很强的人", phraseLeft: "是的", phraseRight: "不是", leftLetter: "J", rightLetter: "P" },
        { id: 18, dimension: "SN", question: "脑海里常冒出一些新点子", phraseLeft: "是的", phraseRight: "不是", leftLetter: "N", rightLetter: "S" },
        { id: 19, dimension: "JP", question: "把事物收拾得有条理，你就会感到高兴", phraseLeft: "是的", phraseRight: "不是，我习惯自由自在和随意", leftLetter: "J", rightLetter: "P" },
        { id: 20, dimension: "JP", question: "你能够很好的控制自己的欲望和外部诱惑", phraseLeft: "是的", phraseRight: "更多时候我会不由自主", leftLetter: "J", rightLetter: "P" },
        { id: 21, dimension: "SN", question: "相对解决问题的结果，你更注重解决的过程和方法", phraseLeft: "是的", phraseRight: "不是", leftLetter: "S", rightLetter: "N" },
        { id: 22, dimension: "SN", question: "解决问题的时候，比起用新的方法，你更愿意用熟悉的方法解决", phraseLeft: "是的", phraseRight: "不是", leftLetter: "S", rightLetter: "N" },
        { id: 23, dimension: "JP", question: "你的内心渴望一次冒险", phraseLeft: "是的", phraseRight: "不是", leftLetter: "P", rightLetter: "J" },
        { id: 24, dimension: "TF", question: "你倾向于凡事都持科学的态度", phraseLeft: "是的", phraseRight: "不是，我比较感性", leftLetter: "T", rightLetter: "F" },
        { id: 25, dimension: "JP", question: "比起事前的计划，你的决定大多基于瞬间的感觉", phraseLeft: "是的", phraseRight: "不是", leftLetter: "P", rightLetter: "J" },
        { id: 26, dimension: "SN", question: "传统的生活方式让你觉得更自在", phraseLeft: "是的", phraseRight: "不是，我渴望新的体验", leftLetter: "S", rightLetter: "N" },
        { id: 27, dimension: "JP", question: "你的桌子、办公台总是整洁而规律", phraseLeft: "是的", phraseRight: "不是", leftLetter: "J", rightLetter: "P" },
        { id: 28, dimension: "EI", question: "独自行走你会觉得舒服", phraseLeft: "是的", phraseRight: "我更愿意找人聊天、参加娱乐活动", leftLetter: "I", rightLetter: "E" },
        { id: 29, dimension: "JP", question: "你常常会急急忙忙赶一件事", phraseLeft: "是的", phraseRight: "不是", leftLetter: "J", rightLetter: "P" },
        { id: 30, dimension: "EI", question: "你喜欢一个人行动", phraseLeft: "是的", phraseRight: "不是，我不喜欢孤苦伶仃", leftLetter: "I", rightLetter: "E" },
        { id: 31, dimension: "TF", question: "对你而言，解决问题本身就是一种乐趣", phraseLeft: "是的", phraseRight: "我更喜欢发现和体验美好的东西", leftLetter: "T", rightLetter: "F" },
        { id: 32, dimension: "SN", question: "喜欢推测、预测和分析", phraseLeft: "是的", phraseRight: "这些对我而言都是浮云，我只想把握好当下", leftLetter: "N", rightLetter: "S" },
        { id: 33, dimension: "TF", question: "喜欢装饰", phraseLeft: "是，喜欢漂亮的，可爱的，华丽的", phraseRight: "不是，服装嘛，只要有一件T恤，一条牛仔裤就足够了", leftLetter: "F", rightLetter: "T" },
        { id: 34, dimension: "EI", question: "很容易与他人成为朋友", phraseLeft: "是的，不管对方是谁，我都能和他和睦相处", phraseRight: "没有必要和所有人都成为朋友，有几个真正的知己就可以", leftLetter: "E", rightLetter: "I" },
        { id: 35, dimension: "TF", question: "喜欢受到他人的关心", phraseLeft: "是的，感觉旁边人在关心我的话，心情当然好咯", phraseRight: "不是，不要过分在意我", leftLetter: "F", rightLetter: "T" },
        { id: 36, dimension: "TF", question: "对周围人的变化很敏感", phraseLeft: "是的，连朋友换个戒指也瞒不了我", phraseRight: "不是，有时候对方换什么衣服否察觉不到", leftLetter: "F", rightLetter: "T" },
        { id: 37, dimension: "EI", question: "经过冗长的社交之后，你会想要离开，独处一下", phraseLeft: "是的，我常有这样的感觉", phraseRight: "没有这种体会", leftLetter: "I", rightLetter: "E" },
        { id: 38, dimension: "JP", question: "喜欢清闲的生活", phraseLeft: "是的，我喜欢轻轻松松的人生", phraseRight: "我喜欢有挑战的人生，不断给自己更高的目标", leftLetter: "P", rightLetter: "J" },
        { id: 39, dimension: "TF", question: "你发现很难谈论自己的情感", phraseLeft: "是的", phraseRight: "不是", leftLetter: "T", rightLetter: "F" },
        { id: 40, dimension: "SN", question: "当你考虑一件事情时，你很少想到事情可能的发展，而是更多关注目的", phraseLeft: "是的", phraseRight: "不是，我更容易陷入对未来可能性的推测中", leftLetter: "S", rightLetter: "N" },
        { id: 41, dimension: "TF", question: "你容易被强烈的情感影响", phraseLeft: "是的", phraseRight: "不是", leftLetter: "F", rightLetter: "T" },
        { id: 42, dimension: "EI", question: "我喜欢一个人独自享受空闲时光，或者在安静的家庭环境中放松", phraseLeft: "是的", phraseRight: "不是", leftLetter: "I", rightLetter: "E" },
        
        // ===== Section 2: 43-93题 =====
        { id: 43, dimension: "TF", question: "做决定时，你倾向于", phraseLeft: "首先依我的逻辑，然后依我的心意", phraseRight: "首先依我的心意，然后依我的逻辑", leftLetter: "T", rightLetter: "F" },
        { id: 44, dimension: "JP", question: "大多数时候，你倾向于", phraseLeft: "随机应变", phraseRight: "事先计划", leftLetter: "P", rightLetter: "J" },
        { id: 45, dimension: "SN", question: "小时候，你更热衷于", phraseLeft: "问为什么，或自己动手拆玩具找到其原理", phraseRight: "绘画和表述，描述和描绘所看到的", leftLetter: "N", rightLetter: "S" },
        { id: 46, dimension: "SN", question: "你倾向通过哪种方式收集信息", phraseLeft: "对目前状况的实际认知", phraseRight: "对有可能发生之事的想象和期望", leftLetter: "S", rightLetter: "N" },
        { id: 47, dimension: "TF", question: "哪种更符合你", phraseLeft: "我很少质询和指责他人，更愿意做一个随和包容的人", phraseRight: "我不想充当老好人，发现他人犯错就会直言不讳指出来", leftLetter: "F", rightLetter: "T" },
        { id: 48, dimension: "SN", question: "你倾向相信", phraseLeft: "我直接的观察和现成的经验", phraseRight: "我的直觉", leftLetter: "S", rightLetter: "N" },
        { id: 49, dimension: "SN", question: "你更愿意被看作是", phraseLeft: "务实的人", phraseRight: "有想象力、有灵感的人", leftLetter: "S", rightLetter: "N" },
        { id: 50, dimension: "SN", question: "哪种更符合你", phraseLeft: "喜欢发掘新点子", phraseRight: "不善于此", leftLetter: "N", rightLetter: "S" },
        { id: 51, dimension: "JP", question: "哪种更符合你", phraseLeft: "喜欢惊喜并适应最后的变化", phraseRight: "不喜欢变化，追求稳定与踏实", leftLetter: "P", rightLetter: "J" },
        { id: 52, dimension: "SN", question: "大多数时候，你是这种人", phraseLeft: "喜欢先纵观全局", phraseRight: "喜欢先掌握细节", leftLetter: "N", rightLetter: "S" },
        { id: 53, dimension: "TF", question: "当受到情感上的伤害或挫折时", phraseLeft: "虽然我觉得受伤，但一旦想通，就会很快从阴影中走出来", phraseRight: "我通常让自己的情绪深陷其中，很难走出来", leftLetter: "T", rightLetter: "F" },
        { id: 54, dimension: "JP", question: "哪一项较常见", phraseLeft: "我准时出席而其他人都迟到", phraseRight: "其他人都准时出席而我迟到", leftLetter: "J", rightLetter: "P" },
        { id: 55, dimension: "JP", question: "如你有一个约见，你是习惯临场发挥还是事先周密准备", phraseLeft: "随机应变，临场发挥", phraseRight: "不周密准备我不安心", leftLetter: "P", rightLetter: "J" },
        { id: 56, dimension: "JP", question: "你是此类型的人", phraseLeft: "喜欢在一段时间里专心于一件事情直到完成", phraseRight: "享受同时进行好几件事情", leftLetter: "J", rightLetter: "P" },
        { id: 57, dimension: "JP", question: "你喜欢", phraseLeft: "有部署、有节奏的工作", phraseRight: "有灵活性、较为松散的工作", leftLetter: "J", rightLetter: "P" },
        { id: 58, dimension: "EI", question: "当不得不主动同生人打交道时，你", phraseLeft: "有点儿担心别人不愿被打搅", phraseRight: "感到自信并且轻松", leftLetter: "I", rightLetter: "E" },
        { id: 59, dimension: "TF", question: "你更擅长", phraseLeft: "运用逻辑，分析及批判思维来解决问题", phraseRight: "运用人际关系解决问题", leftLetter: "T", rightLetter: "F" },
        { id: 60, dimension: "JP", question: "疲惫地下班回家时，哪种描述更像你", phraseLeft: "再累也收拾整齐了再休息", phraseRight: "扔下包倒床就睡", leftLetter: "J", rightLetter: "P" },
        { id: 61, dimension: "EI", question: "下面哪个更符合你", phraseLeft: "在不与人接触的场合，我充满了生命的愉悦", phraseRight: "哪怕喧嚣嘈杂一点，也比一个人孤伶伶呆着强", leftLetter: "I", rightLetter: "E" },
        { id: 62, dimension: "JP", question: "选择较符合你的词", phraseLeft: "准时", phraseRight: "闲适、悠然", leftLetter: "J", rightLetter: "P" },
        { id: 63, dimension: "JP", question: "你选择的生活充满着", phraseLeft: "自然发生和弹性", phraseRight: "日程表和组织", leftLetter: "P", rightLetter: "J" },
        { id: 64, dimension: "JP", question: "若你有时间和金钱，你的朋友邀请你到国外度假，并且在前一天才通知，你会", phraseLeft: "必须先坚持我的时间表", phraseRight: "立刻收拾行装", leftLetter: "J", rightLetter: "P" },
        { id: 65, dimension: "SN", question: "哪种更符合你", phraseLeft: "表面传统，其实内心是开放而热烈的，渴望挑战自己", phraseRight: "表面很开放，但只是想做自己，内心其实是保守而传统的", leftLetter: "N", rightLetter: "S" },
        { id: 66, dimension: "EI", question: "对于应酬中逢场作戏、聪明圆融的人，你的看法是", phraseLeft: "不理解，也无法接受人们快速地相熟热络，而又骨底淡薄", phraseRight: "看应酬的目的是什么，只要目的是有益的，这些也都无所谓了", leftLetter: "I", rightLetter: "E" },
        { id: 67, dimension: "TF", question: "只要有爱，什么都可以原谅", phraseLeft: "不认同，就算相爱，凡事都是有分寸的", phraseRight: "认同，爱情能冲淡一切不快", leftLetter: "T", rightLetter: "F" },
        { id: 68, dimension: "EI", question: "马上能叫出五个朋友的名字", phraseLeft: "不要说是5个，让我说出10个人也没问题呀", phraseRight: "突然让我叫出5个人的名字，想不起来呀！天啊，难道我朋友这么少吗", leftLetter: "E", rightLetter: "I" },
        { id: 69, dimension: "EI", question: "碰到熟人，下意识躲避", phraseLeft: "常常这样", phraseRight: "不常这样", leftLetter: "I", rightLetter: "E" },
        { id: 70, dimension: "SN", question: "对你更具吸引力的人是", phraseLeft: "聪明而反应敏捷的人", phraseRight: "稳重而脚踏实地的人", leftLetter: "N", rightLetter: "S" },
        { id: 71, dimension: "TF", question: "你倾向比较能够察觉到", phraseLeft: "当人们不合逻辑时", phraseRight: "当人们需要情感上的支持时", leftLetter: "T", rightLetter: "F" },
        { id: 72, dimension: "EI", question: "当要去见陌生人时，你通常", phraseLeft: "多少有些不情愿", phraseRight: "不感到难为情", leftLetter: "I", rightLetter: "E" },
        { id: 73, dimension: "JP", question: "哪种更符合你", phraseLeft: "凡事追求个性，完全凭自己的兴趣，没有固定的程式", phraseRight: "传统而保守，不喜欢标新立异", leftLetter: "P", rightLetter: "J" },
        { id: 74, dimension: "SN", question: "哪种更符合你", phraseLeft: "过于抽象，因此在必要的后续行动上不切实际", phraseRight: "沉浸于细节，导致视野不开阔", leftLetter: "N", rightLetter: "S" },
        { id: 75, dimension: "EI", question: "你倾向拥有", phraseLeft: "很多认识的人和很亲密的朋友", phraseRight: "一些很亲密的朋友和一些认识的人", leftLetter: "E", rightLetter: "I" },
        { id: 76, dimension: "TF", question: "当遇到聚会中第一次见面的人对你很热情时，你会", phraseLeft: "很高兴，情绪会受到感染，并对其产生好感", phraseRight: "热情应付，但心存一丝疑虑：对方为什么要这样热情，是否有其他目的", leftLetter: "F", rightLetter: "T" },
        { id: 77, dimension: "TF", question: "你更容易被认为是一个", phraseLeft: "很理性的人", phraseRight: "很重感情的人", leftLetter: "T", rightLetter: "F" },
        { id: 78, dimension: "EI", question: "在同学聚会中，你通常", phraseLeft: "较安静并保留，直到我觉得舒服", phraseRight: "整体来说很健谈", leftLetter: "I", rightLetter: "E" },
        { id: 79, dimension: "JP", question: "准备搭车远行时，哪种更符合你", phraseLeft: "临行前才匆匆忙忙收拾，赶到车站车已经差不多要出发了……谁叫我是个慢性子呢", phraseRight: "早早收拾好行李，第二天提前很早就去到车站，发现我是第一个来候车的人", leftLetter: "P", rightLetter: "J" },
        { id: 80, dimension: "JP", question: "哪种意境更符合你", phraseLeft: "人生就像一场旅行，不必在意目的地，在乎的是沿途的风景和看风景的心情", phraseRight: "人生需要树立目标并为之奋斗，专注人生目标的人往往无暇欣赏路途美景", leftLetter: "P", rightLetter: "J" },
        { id: 81, dimension: "SN", question: "哪种描述较符合你", phraseLeft: "如果对于一个东西没有一套合理的系统的解释，我就感觉搞不清楚，一片模糊", phraseRight: "享受生活和现实，给什么东西都进行抽象和解释，太累了", leftLetter: "N", rightLetter: "S" },
        { id: 82, dimension: "SN", question: "闲暇时候，你更愿意看哪方面的书", phraseLeft: "摄影", phraseRight: "哲学思辨", leftLetter: "S", rightLetter: "N" },
        { id: 83, dimension: "JP", question: "你偏好", phraseLeft: "事先知道约会的行程：要去哪里，有谁参加、我会在那里多久", phraseRight: "让约会自然地发生，不做太多事先的计划", leftLetter: "J", rightLetter: "P" },
        { id: 84, dimension: "TF", question: "认识你的人倾向于形容你为", phraseLeft: "逻辑和明确", phraseRight: "热情而敏感", leftLetter: "T", rightLetter: "F" },
        { id: 85, dimension: "EI", question: "好朋友倾向对你说", phraseLeft: "你难道不可以安静一会儿吗？", phraseRight: "可以请你从你的世界中出来一下吗？", leftLetter: "E", rightLetter: "I" },
        { id: 86, dimension: "EI", question: "你倾向从何处得到力量", phraseLeft: "朋友", phraseRight: "自己的想法", leftLetter: "E", rightLetter: "I" },
        { id: 87, dimension: "TF", question: "与朋友交往时，你倾向于看重", phraseLeft: "情感上的相容性：对对方情感上的需求很敏感", phraseRight: "智慧上的相容性：沟通重要的想法；客观地讨论和辩论事情", leftLetter: "F", rightLetter: "T" },
        { id: 88, dimension: "SN", question: "当你和一个朋友放松聊天时，你偏向谈论", phraseLeft: "实际的、具体的，关于\"此时此地\"的事物。例如，我也许会谈论即将要参加的旅程", phraseRight: "未来，关于改进或发明事物和生活的种种可能性。例如，我也许会谈论一个新的科学发明", leftLetter: "S", rightLetter: "N" },
        { id: 89, dimension: "TF", question: "当和朋友约定好见面", phraseLeft: "若我所约的人来迟了，我常会不高兴", phraseRight: "一点儿都不在乎，因为我自己常常迟到", leftLetter: "T", rightLetter: "F" },
        { id: 90, dimension: "EI", question: "哪种更接近朋友对你的评价", phraseLeft: "外表平静，大家都说我闷骚", phraseRight: "开朗活泼，大家都说我太聒噪了", leftLetter: "I", rightLetter: "E" },
        { id: 91, dimension: "TF", question: "当你不同意朋友的想法时", phraseLeft: "我尽可能地避免伤害对方的感情；若是会对对方造成伤害的话，我就不会说", phraseRight: "我通常毫无保留地说话，并且对朋友直言不讳，因为对的就是对的", leftLetter: "F", rightLetter: "T" },
        { id: 92, dimension: "TF", question: "周围的朋友们都说你是很冷静的人", phraseLeft: "我说话做事比较冲动，并非一个冷静的人", phraseRight: "是，我的性格是孤言寡语，非常冷静", leftLetter: "F", rightLetter: "T" },
        { id: 93, dimension: "SN", question: "相比之下，你更欣赏", phraseLeft: "实业家，洛克菲勒", phraseRight: "科学家，爱因斯坦", leftLetter: "S", rightLetter: "N" }
    ],

    // 16 Personality Types (unchanged)
    types: {
        "INTJ": {
            name: "INTJ",
            chineseName: "建筑师",
            englishName: "Architect",
            group: "Analysts",
            groupCN: "分析家",
            color: "#4A90A4",
            gradient: "linear-gradient(135deg, #4A90A4 0%, #2C5F6E 100%)",
            description: "富有想象力和战略性的思考者，拥有强大的内在动力去实现自己的目标。",
            strengths: ["独立思考", "战略眼光", "追求效率", "坚持原则"],
            weaknesses: ["过于批判", "情感表达困难", "完美主义", "不善于社交"],
            relationships: "倾向于建立深度的、有意义的关系，但可能显得冷漠或疏远。重视智识上的交流和相互尊重。",
            career: "适合需要战略思维、独立工作和技术专长的领域，如科学、技术、金融、咨询等。",
            keywords: ["独立", "战略", "理性", "创新"]
        },
        "INTP": {
            name: "INTP",
            chineseName: "逻辑学家",
            englishName: "Logician",
            group: "Analysts",
            groupCN: "分析家",
            color: "#7B8FA1",
            gradient: "linear-gradient(135deg, #7B8FA1 0%, #4A5568 100%)",
            description: "富有创造力的发明家，对知识有着无尽的渴望。喜欢理论和抽象概念。",
            strengths: ["分析能力", "创新能力", "客观理性", "独立思考"],
            weaknesses: ["忽视情感", "拖延症", "难以集中", "与社会脱节"],
            relationships: "可能在表达情感方面有困难，但重视智识上的深度交流。倾向于选择少数几个亲密朋友。",
            career: "适合需要深入研究、理论分析和创造性解决问题的领域，如研究、工程、编程、哲学等。",
            keywords: ["理性", "创新", "好奇", "独立"]
        },
        "ENTJ": {
            name: "ENTJ",
            chineseName: "指挥官",
            englishName: "Commander",
            group: "Analysts",
            groupCN: "分析家",
            color: "#E85D4C",
            gradient: "linear-gradient(135deg, #E85D4C 0%, #C0392B 100%)",
            description: "大胆、富有想象力的领导者，总是寻求改善和创新。善于制定长期战略。",
            strengths: ["领导能力", "决策果断", "自信坚定", "战略思维"],
            weaknesses: ["缺乏耐心", "过于严厉", "不易接受批评", "控制欲强"],
            relationships: "直接坦诚，可能显得强势。但对重要的人非常忠诚，愿意为关系付出努力。",
            career: "适合需要领导能力、战略规划和决策能力的领域，如企业管理、创业、政治、法律等。",
            keywords: ["领导", "果断", "自信", "战略"]
        },
        "ENTP": {
            name: "ENTP",
            chineseName: "辩论家",
            englishName: "Debater",
            group: "Analysts",
            groupCN: "分析家",
            color: "#FF8C42",
            gradient: "linear-gradient(135deg, #FF8C42 0%, #E67E22 100%)",
            description: "聪明好奇的思想者，喜欢挑战现状。善于发现问题并寻找创造性的解决方案。",
            strengths: ["创意丰富", "思维敏捷", "善于沟通", "喜欢辩论"],
            weaknesses: ["难以专注", "忽视细节", "情绪化", "喜欢争论"],
            relationships: "喜欢智识上的刺激和有趣的对话。可能在承诺方面有困难，但对朋友非常忠诚。",
            career: "适合需要创新、沟通和灵活应变能力的领域，如营销、创业、公关、咨询、发明等。",
            keywords: ["创新", "辩论", "活力", "聪明"]
        },
        "INFJ": {
            name: "INFJ",
            chineseName: "提倡者",
            englishName: "Advocate",
            group: "Diplomats",
            groupCN: "外交家",
            color: "#9B59B6",
            gradient: "linear-gradient(135deg, #9B59B6 0%, #7D3C98 100%)",
            description: "安静而富有同理心的理想主义者，有着强烈的内在价值观和对帮助他人的渴望。",
            strengths: ["同理心", "洞察力", "创造力", "坚持理想"],
            weaknesses: ["过度付出", "完美主义", "逃避冲突", "过于敏感"],
            relationships: "非常重视深度和真实性。倾向于建立少数但深厚的关系，对朋友忠诚无比。",
            career: "适合需要洞察力、同理心和创造力的领域，如心理咨询、教育、艺术、写作、社会工作等。",
            keywords: ["理想", "同理", "洞察", "创造"]
        },
        "INFP": {
            name: "INFP",
            chineseName: "调停者",
            englishName: "Mediator",
            group: "Diplomats",
            groupCN: "外交家",
            color: "#1ABC9C",
            gradient: "linear-gradient(135deg, #1ABC9C 0%, #16A085 100%)",
            description: "富有诗意、善良的梦想家，始终在寻找生命的意义和价值。",
            strengths: ["创意丰富", "同理心强", "理想主义", "忠诚"],
            weaknesses: ["不切实际", "逃避现实", "过度自我牺牲", "难以做决定"],
            relationships: "重视情感深度和精神连接。倾向于寻找灵魂伴侣，对爱情充满理想。",
            career: "适合需要创造力、同理心和自我表达的领域，如艺术、写作、音乐、心理辅导、志愿服务等。",
            keywords: ["理想", "创意", "善良", "敏感"]
        },
        "ENFJ": {
            name: "ENFJ",
            chineseName: "主人公",
            englishName: "Protagonist",
            group: "Diplomats",
            groupCN: "外交家",
            color: "#F39C12",
            gradient: "linear-gradient(135deg, #F39C12 0%, #D68910 100%)",
            description: "富有魅力的领导者，能够激励和启发他人。真诚地关心他人的成长和幸福。",
            strengths: ["领导力", "同理心", "沟通能力", "魅力十足"],
            weaknesses: ["过度操劳", "过于理想化", "难以接受批评", "忽视自己"],
            relationships: "非常重视人际关系，喜欢帮助他人成长。善于协调和激励团队。",
            career: "适合需要领导力、沟通技巧和人际关系的领域，如管理、教育、咨询、公共关系、演艺等。",
            keywords: ["领导", "激励", "关怀", "魅力"]
        },
        "ENFP": {
            name: "ENFP",
            chineseName: "竞选者",
            englishName: "Campaigner",
            group: "Diplomats",
            groupCN: "外交家",
            color: "#E74C3C",
            gradient: "linear-gradient(135deg, #E74C3C 0%, #C0392B 100%)",
            description: "热情洋溢、富有创意的社交达人，总是充满新的想法和可能性。",
            strengths: ["热情洋溢", "创意丰富", "善于激励", "适应力强"],
            weaknesses: ["难以专注", "情绪波动", "逃避困难", "过于理想化"],
            relationships: "热爱社交，善于与人建立联系。重视情感自由，可能在承诺方面有困难。",
            career: "适合需要创造力、沟通能力和热情激励的领域，如营销、艺术、创业、写作、表演等。",
            keywords: ["热情", "创意", "活力", "激励"]
        },
        "ISTJ": {
            name: "ISTJ",
            chineseName: "物流师",
            englishName: "Logistician",
            group: "Sentinels",
            groupCN: "守卫者",
            color: "#34495E",
            gradient: "linear-gradient(135deg, #34495E 0%, #2C3E50 100%)",
            description: "务实、可靠的传统主义者。重视责任和承诺，致力于维护秩序和稳定。",
            strengths: ["可靠负责", "注重细节", "有条理", "坚持不懈"],
            weaknesses: ["僵硬死板", "不善于变通", "难以接受新事物", "情感表达困难"],
            relationships: "忠诚可靠，对承诺非常重视。可能在表达情感方面较为含蓄，但内心深处非常珍视家人和朋友。",
            career: "适合需要可靠性、组织能力和注重细节的领域，如会计、金融、管理、物流、医疗等。",
            keywords: ["可靠", "负责", "传统", "务实"]
        },
        "ISFJ": {
            name: "ISFJ",
            chineseName: "守卫者",
            englishName: "Defender",
            group: "Sentinels",
            groupCN: "守卫者",
            color: "#27AE60",
            gradient: "linear-gradient(135deg, #27AE60 0%, #1E8449 100%)",
            description: "温暖、体贴的守护者。总是把别人的需求放在自己之前，默默付出。",
            strengths: ["细心体贴", "忠诚可靠", "勤奋努力", "善于照顾"],
            weaknesses: ["过度付出", "难以拒绝", "自我价值感低", "过度自责"],
            relationships: "非常重视家庭和亲密关系。愿意为所爱的人做任何事情，有时会忽略自己的需求。",
            career: "适合需要关怀、组织能力和服务精神的领域，如护理、教育、社会工作、行政管理等。",
            keywords: ["关怀", "忠诚", "服务", "细心"]
        },
        "ESTJ": {
            name: "ESTJ",
            chineseName: "总经理",
            englishName: "Executive",
            group: "Sentinels",
            groupCN: "守卫者",
            color: "#5D6D7E",
            gradient: "linear-gradient(135deg, #5D6D7E 0%, #34495E 100%)",
            description: "务实、高效的组织者。善于管理事务，确保工作按时完成并达到标准。",
            strengths: ["领导能力", "注重效率", "善于组织", "负责任"],
            weaknesses: ["过于严厉", "缺乏灵活性", "不善于情感表达", "判断性过强"],
            relationships: "直接坦诚，重视承诺和责任。可能显得强势或缺乏耐心，但内心关心家人和朋友。",
            career: "适合需要领导、组织和管理能力的领域，如企业管理、军事、法律、金融、行政等。",
            keywords: ["组织", "效率", "负责", "传统"]
        },
        "ESFJ": {
            name: "ESFJ",
            chineseName: "执政官",
            englishName: "Consul",
            group: "Sentinels",
            groupCN: "守卫者",
            color: "#F5B041",
            gradient: "linear-gradient(135deg, #F5B041 0%, #E67E22 100%)",
            description: "热情、体贴的社交达人。善于照顾他人，喜欢创造和谐愉快的氛围。",
            strengths: ["善于社交", "关怀他人", "责任感强", "务实可靠"],
            weaknesses: ["过于关注他人", "难以接受批评", "过度操劳", "害怕冲突"],
            relationships: "非常重视人际关系，喜欢为他人服务。善于组织社交活动，关心朋友和家人的需求。",
            career: "适合需要人际交往、服务精神和组织能力的领域，如教育、护理、服务业、人力资源、行政等。",
            keywords: ["关怀", "社交", "服务", "和谐"]
        },
        "ISTP": {
            name: "ISTP",
            chineseName: "鉴赏家",
            englishName: "Virtuoso",
            group: "Explorers",
            groupCN: "探险家",
            color: "#85929E",
            gradient: "linear-gradient(135deg, #85929E 0%, #5D6D7E 100%)",
            description: "大胆实用的动手者，善于分析问题的本质。喜欢探索事物的运作方式。",
            strengths: ["动手能力", "冷静分析", "适应力强", "务实"],
            weaknesses: ["情感封闭", "冒险精神过度", "难以承诺", "不善于表达"],
            relationships: "重视独立和自由，可能显得冷漠或疏远。但对于重要的人非常忠诚和关心。",
            career: "适合需要动手能力、分析思维和解决实际问题的领域，如工程、技术、机械、体育、艺术等。",
            keywords: ["实用", "分析", "动手", "冷静"]
        },
        "ISFP": {
            name: "ISFP",
            chineseName: "探险家",
            englishName: "Adventurer",
            group: "Explorers",
            groupCN: "探险家",
            color: "#76D7C4",
            gradient: "linear-gradient(135deg, #76D7C4 0%, #48C9B0 100%)",
            description: "富有艺术感的探险家，敏感而温柔。注重个人价值观和美学体验。",
            strengths: ["艺术天赋", "敏感细腻", "适应力强", "善于观察"],
            weaknesses: ["逃避冲突", "难以做决定", "过度自我保护", "不善于规划"],
            relationships: "重视个人空间和自由，但对于亲密关系非常忠诚和投入。倾向于用行动表达关心。",
            career: "适合需要创意、艺术感和动手能力的领域，如艺术、设计、音乐、摄影、烹饪、园艺等。",
            keywords: ["艺术", "自由", "敏感", "探索"]
        },
        "ESTP": {
            name: "ESTP",
            chineseName: "企业家",
            englishName: "Entrepreneur",
            group: "Explorers",
            groupCN: "探险家",
            color: "#E74C3C",
            gradient: "linear-gradient(135deg, #E74C3C 0%, #C0392B 100%)",
            description: "精力充沛、喜欢冒险的行动派。善于抓住机会，享受当下的刺激。",
            strengths: ["行动力强", "善于谈判", "适应力强", "魅力十足"],
            weaknesses: ["缺乏耐心", "冲动冒险", "忽视长远", "不善于规划"],
            relationships: "喜欢社交和刺激，可能在承诺方面有困难。但对朋友非常仗义和忠诚。",
            career: "适合需要行动力、谈判技巧和应变能力的领域，如销售、创业、体育、娱乐、商务等。",
            keywords: ["行动", "冒险", "活力", "现实"]
        },
        "ESFP": {
            name: "ESFP",
            chineseName: "表演者",
            englishName: "Entertainer",
            group: "Explorers",
            groupCN: "探险家",
            color: "#FF6B6B",
            gradient: "linear-gradient(135deg, #FF6B6B 0%, #EE5A5A 100%)",
            description: "热情奔放、充满活力的表演者。喜欢成为焦点，给周围带来欢乐和能量。",
            strengths: ["热情洋溢", "善于表演", "适应力强", "富有感染力"],
            weaknesses: ["难以专注", "逃避责任", "过于冲动", "害怕独处"],
            relationships: "热爱社交和聚会，喜欢成为人群中的焦点。重视当下的快乐和情感连接。",
            career: "适合需要表演、沟通和激发热情的领域，如演艺、娱乐、销售、服务业、教育等。",
            keywords: ["热情", "表演", "活力", "社交"]
        }
    }
};
