// MBTI Test Data
// 60 Questions covering 4 dimensions: E/I, S/N, T/F, J/P (15 questions each)
// 16 Personality Types with complete data

var MBTI_DATA = {
    questions: [
        // E/I Dimension (23 questions)
        { id: 1, dimension: "EI", question: "当你要外出一整天，你会：", optionA: { text: "计划你要做什么和在什么时候做", score: "E" }, optionB: { text: "说去就去", score: "I" } },
        { id: 2, dimension: "EI", question: "你认为自己是一个：", optionA: { text: "较为随兴所至的人", score: "E" }, optionB: { text: "较为有条理的人", score: "I" } },
        { id: 3, dimension: "EI", question: "假如你是一位老师，你会选教：", optionA: { text: "以事实为主的课程", score: "E" }, optionB: { text: "涉及理论的课程", score: "I" } },
        { id: 4, dimension: "EI", question: "你通常：", optionA: { text: "与人容易混熟", score: "E" }, optionB: { text: "比较沉静或矜持", score: "I" } },
        { id: 5, dimension: "EI", question: "一般来说，你和哪些人比较合得来？", optionA: { text: "富于想象力的人", score: "E" }, optionB: { text: "现实的人", score: "I" } },
        { id: 6, dimension: "EI", question: "你是否经常让：", optionA: { text: "你的情感支配你的理智", score: "E" }, optionB: { text: "你的理智主宰你的情感", score: "I" } },
        { id: 7, dimension: "EI", question: "处理许多事情上，你会喜欢：", optionA: { text: "凭兴所至行事", score: "E" }, optionB: { text: "按照计划行事", score: "I" } },
        { id: 8, dimension: "EI", question: "你是否：", optionA: { text: "容易让人了解", score: "E" }, optionB: { text: "难于让人了解", score: "I" } },
        { id: 9, dimension: "EI", question: "按照程序表做事：", optionA: { text: "合你心意", score: "E" }, optionB: { text: "令你感到束缚", score: "I" } },
        { id: 10, dimension: "EI", question: "当你有一份特别的任务，你会喜欢：", optionA: { text: "开始前小心组织计划", score: "E" }, optionB: { text: "边做边找须做什么", score: "I" } },
        { id: 11, dimension: "EI", question: "在大多数情况下，你会选择：", optionA: { text: "顺其自然", score: "E" }, optionB: { text: "按程序表做事", score: "I" } },
        { id: 12, dimension: "EI", question: "大多数人会说你是一个：", optionA: { text: "重视自我隐私的人", score: "E" }, optionB: { text: "非常坦率开放的人", score: "I" } },
        { id: 13, dimension: "EI", question: "你宁愿被人认为是一个：", optionA: { text: "实事求是的人", score: "E" }, optionB: { text: "机灵的人", score: "I" } },
        { id: 14, dimension: "EI", question: "在一大群人当中，通常是：", optionA: { text: "你介绍大家认识", score: "E" }, optionB: { text: "别人介绍你", score: "I" } },
        { id: 15, dimension: "EI", question: "你会跟哪些人做朋友？", optionA: { text: "常提出新主意的", score: "E" }, optionB: { text: "脚踏实地的", score: "I" } },
        { id: 16, dimension: "EI", question: "你倾向：", optionA: { text: "重视感情多于逻辑", score: "E" }, optionB: { text: "重视逻辑多于感情", score: "I" } },
        { id: 17, dimension: "EI", question: "你比较喜欢：", optionA: { text: "坐观事情发展才作计划", score: "E" }, optionB: { text: "很早就作计划", score: "I" } },
        { id: 18, dimension: "EI", question: "你喜欢花很多的时间：", optionA: { text: "一个人独处", score: "E" }, optionB: { text: "和别人在一起", score: "I" } },
        { id: 19, dimension: "EI", question: "与很多人一起会：", optionA: { text: "令你活力培增", score: "E" }, optionB: { text: "常常令你心力憔悴", score: "I" } },
        { id: 20, dimension: "EI", question: "你比较喜欢：", optionA: { text: "很早便把约会、社交聚集等事情安排妥当", score: "E" }, optionB: { text: "无拘无束，看当时有什么好玩就做什么", score: "I" } },
        { id: 21, dimension: "EI", question: "计划一个旅程时，你较喜欢：", optionA: { text: "大部分的时间都是跟当天的感觉行事", score: "E" }, optionB: { text: "事先知道大部分的日子会做什么", score: "I" } },
        { id: 22, dimension: "EI", question: "在社交聚会中，你：", optionA: { text: "有时感到郁闷", score: "E" }, optionB: { text: "常常乐在其中", score: "I" } },
        { id: 23, dimension: "EI", question: "你通常：", optionA: { text: "和别人容易混熟", score: "E" }, optionB: { text: "趋向自处一隅", score: "I" } },
        
        // S/N Dimension (23 questions)
        { id: 24, dimension: "SN", question: "哪些人会更吸引你？", optionA: { text: "一个思想敏捷及非常聪颖的人", score: "N" }, optionB: { text: "实事求是，具丰富常识的人", score: "S" } },
        { id: 25, dimension: "SN", question: "在日常工作中，你会：", optionA: { text: "颇为喜欢处理迫使你分秒必争的突发", score: "S" }, optionB: { text: "通常预先计划，以免要在压力下工作", score: "N" } },
        { id: 26, dimension: "SN", question: "你认为别人一般：", optionA: { text: "要花很长时间才认识你", score: "N" }, optionB: { text: "用很短的时间便认识你", score: "S" } },
        { id: 27, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "注重隐私", score: "N" }, optionB: { text: "坦率开放", score: "S" } },
        { id: 28, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "预先安排的", score: "N" }, optionB: { text: "无计划的", score: "S" } },
        { id: 29, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "抽象", score: "N" }, optionB: { text: "具体", score: "S" } },
        { id: 30, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "温柔", score: "S" }, optionB: { text: "坚定", score: "N" } },
        { id: 31, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "思考", score: "N" }, optionB: { text: "感受", score: "S" } },
        { id: 32, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "事实", score: "S" }, optionB: { text: "意念", score: "N" } },
        { id: 33, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "冲动", score: "S" }, optionB: { text: "决定", score: "N" } },
        { id: 34, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "热衷", score: "S" }, optionB: { text: "文静", score: "N" } },
        { id: 35, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "文静", score: "N" }, optionB: { text: "外向", score: "S" } },
        { id: 36, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "有系统", score: "N" }, optionB: { text: "随意", score: "S" } },
        { id: 37, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "理论", score: "N" }, optionB: { text: "肯定", score: "S" } },
        { id: 38, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "敏感", score: "S" }, optionB: { text: "公正", score: "N" } },
        { id: 39, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "令人信服", score: "N" }, optionB: { text: "感人的", score: "S" } },
        { id: 40, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "声明", score: "N" }, optionB: { text: "概念", score: "S" } },
        { id: 41, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "不受约束", score: "S" }, optionB: { text: "预先安排", score: "N" } },
        { id: 42, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "矜持", score: "N" }, optionB: { text: "健谈", score: "S" } },
        { id: 43, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "有条不紊", score: "N" }, optionB: { text: "不拘小节", score: "S" } },
        { id: 44, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "意念", score: "N" }, optionB: { text: "实况", score: "S" } },
        { id: 45, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "同情怜悯", score: "S" }, optionB: { text: "远见", score: "N" } },
        { id: 46, dimension: "SN", question: "在下列词语中，你更倾向于：", optionA: { text: "利益", score: "S" }, optionB: { text: "祝福", score: "N" } },
        
        // T/F Dimension (23 questions)
        { id: 47, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "务实的", score: "T" }, optionB: { text: "理论的", score: "F" } },
        { id: 48, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "朋友不多", score: "I" }, optionB: { text: "朋友众多", score: "E" } },
        { id: 49, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "有系统", score: "T" }, optionB: { text: "即兴", score: "F" } },
        { id: 50, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "富想象的", score: "N" }, optionB: { text: "以事论事", score: "S" } },
        { id: 51, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "亲切的", score: "F" }, optionB: { text: "客观的", score: "T" } },
        { id: 52, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "客观的", score: "T" }, optionB: { text: "热情的", score: "F" } },
        { id: 53, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "建造", score: "S" }, optionB: { text: "发明", score: "N" } },
        { id: 54, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "文静", score: "I" }, optionB: { text: "爱合群", score: "E" } },
        { id: 55, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "理论", score: "N" }, optionB: { text: "事实", score: "S" } },
        { id: 56, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "富同情", score: "F" }, optionB: { text: "合逻辑", score: "T" } },
        { id: 57, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "具分析力", score: "T" }, optionB: { text: "多愁善感", score: "F" } },
        { id: 58, dimension: "TF", question: "在下列词语中，你更倾向于：", optionA: { text: "合情合理", score: "T" }, optionB: { text: "令人着迷", score: "F" } },
        { id: 59, dimension: "TF", question: "当你要在一个星期内完成一个大项目，你在开始的时候会：", optionA: { text: "把要做的不同工作依次列出", score: "T" }, optionB: { text: "马上动工", score: "F" } },
        { id: 60, dimension: "TF", question: "在社交场合中，你经常会感到：", optionA: { text: "与某些人很难打开话匣儿和保持对话", score: "I" }, optionB: { text: "与多数人都能从容地长谈", score: "E" } },
        { id: 61, dimension: "TF", question: "要做许多人也做的事，你比较喜欢：", optionA: { text: "按照一般认可的方法去做", score: "S" }, optionB: { text: "构想一个自己的想法", score: "N" } },
        { id: 62, dimension: "TF", question: "你刚认识的朋友能否说出你的兴趣？", optionA: { text: "马上可以", score: "E" }, optionB: { text: "要待他们真正了解你之后才可以", score: "I" } },
        { id: 63, dimension: "TF", question: "你通常较喜欢的科目是：", optionA: { text: "讲授概念和原则的", score: "N" }, optionB: { text: "讲授事实和数据的", score: "S" } },
        { id: 64, dimension: "TF", question: "哪个是较高的赞誉，或称许为？", optionA: { text: "一贯感性的人", score: "F" }, optionB: { text: "一贯理性的人", score: "T" } },
        { id: 65, dimension: "TF", question: "你认为按照程序表做事：", optionA: { text: "有时是需要的，但一般来说你不大喜欢这样做", score: "P" }, optionB: { text: "大多数情况下是有帮助而且是你喜欢做的", score: "J" } },
        { id: 66, dimension: "TF", question: "和一群人在一起，你通常会选：", optionA: { text: "跟你很熟悉的个别人谈话", score: "I" }, optionB: { text: "参与大伙的谈话", score: "E" } },
        { id: 67, dimension: "TF", question: "在社交聚面上，你会：", optionA: { text: "是说话很多的一个", score: "E" }, optionB: { text: "让别人多说话", score: "I" } },
        { id: 68, dimension: "TF", question: "把周末期间要完成的事列成清单，这个主意会：", optionA: { text: "合你意", score: "J" }, optionB: { text: "使你提不起劲", score: "P" } },
        { id: 69, dimension: "TF", question: "哪个是较高的赞誉，或称许为：", optionA: { text: "能干的", score: "T" }, optionB: { text: "富有同情心", score: "F" } },
        
        // J/P Dimension (24 questions)
        { id: 70, dimension: "JP", question: "你通常喜欢：", optionA: { text: "事先安排你的社交约会", score: "J" }, optionB: { text: "随兴之所至做事", score: "P" } },
        { id: 71, dimension: "JP", question: "总的说来，要做一个大型作业时，你会选：", optionA: { text: "边做边想该做什么", score: "P" }, optionB: { text: "首先把工作按步细分", score: "J" } },
        { id: 72, dimension: "JP", question: "你能否滔滔不绝地与人聊天：", optionA: { text: "只限于跟你有共同兴趣的人", score: "I" }, optionB: { text: "几乎跟任何人都可以", score: "E" } },
        { id: 73, dimension: "JP", question: "你会：", optionA: { text: "跟随一些证明有效的方法", score: "S" }, optionB: { text: "分析还有什么毛病，及针对尚未解决的难题", score: "N" } },
        { id: 74, dimension: "JP", question: "为乐趣而阅读时，你会：", optionA: { text: "喜欢奇特或创新的表达方式", score: "N" }, optionB: { text: "喜欢作者直话直说", score: "S" } },
        { id: 75, dimension: "JP", question: "你宁愿替哪一类上司（或者老师）工作？", optionA: { text: "天性淳良，但常常前后不一的", score: "F" }, optionB: { text: "言词尖锐但永远合乎逻辑的", score: "T" } },
        { id: 76, dimension: "JP", question: "你做事多数是：", optionA: { text: "按当天心情去做", score: "P" }, optionB: { text: "照拟好的程序表去做", score: "J" } },
        { id: 77, dimension: "JP", question: "你是否：", optionA: { text: "可以和任何人按需求从容地交谈", score: "E" }, optionB: { text: "只是对某些人或在某种情况下才可以畅所欲言", score: "I" } },
        { id: 78, dimension: "JP", question: "要作决定时，你认为比较重要的是：", optionA: { text: "据事实衡量", score: "T" }, optionB: { text: "考虑他人的感受和意见", score: "F" } },
        { id: 79, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "想象的", score: "N" }, optionB: { text: "真实的", score: "S" } },
        { id: 80, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "仁慈慷慨的", score: "F" }, optionB: { text: "意志坚定的", score: "T" } },
        { id: 81, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "公正的", score: "T" }, optionB: { text: "有关怀心", score: "F" } },
        { id: 82, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "制作", score: "S" }, optionB: { text: "设计", score: "N" } },
        { id: 83, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "可能性", score: "N" }, optionB: { text: "必然性", score: "S" } },
        { id: 84, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "温柔", score: "F" }, optionB: { text: "力量", score: "T" } },
        { id: 85, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "实际", score: "S" }, optionB: { text: "多愁善感", score: "F" } },
        { id: 86, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "制造", score: "S" }, optionB: { text: "创造", score: "N" } },
        { id: 87, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "新颖的", score: "N" }, optionB: { text: "已知的", score: "S" } },
        { id: 88, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "同情", score: "F" }, optionB: { text: "分析", score: "T" } },
        { id: 89, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "坚持己见", score: "T" }, optionB: { text: "温柔有爱心", score: "F" } },
        { id: 90, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "具体的", score: "S" }, optionB: { text: "抽象的", score: "N" } },
        { id: 91, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "全心投入", score: "F" }, optionB: { text: "有决心的", score: "T" } },
        { id: 92, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "能干", score: "T" }, optionB: { text: "仁慈", score: "F" } },
        { id: 93, dimension: "JP", question: "在下列词语中，你更倾向于：", optionA: { text: "系统", score: "J" }, optionB: { text: "灵活", score: "P" } }
    ],

    // 16 Personality Types
    types: {
        "INTJ": {
            name: "INTJ",
            chineseName: "建筑师",
            englishName: "Architect",
            group: "Analysts",
            groupCN: "分析家",
            color: "#4A90A4",
            gradient: "linear-gradient(135deg, #4A90A4 0%, #2C5F6E 100%)",
            description: "富有想象力和战略性的思考者，拥有强大的内在动力去实现自己的目标。",
            strengths: ["独立思考", "战略眼光", "追求效率", "坚持原则"],
            weaknesses: ["过于批判", "情感表达困难", "完美主义", "不善于社交"],
            relationships: "倾向于建立深度的、有意义的关系，但可能显得冷漠或疏远。重视智识上的交流和相互尊重。",
            career: "适合需要战略思维、独立工作和技术专长的领域，如科学、技术、金融、咨询等。",
            keywords: ["独立", "战略", "理性", "创新"]
        },
        "INTP": {
            name: "INTP",
            chineseName: "逻辑学家",
            englishName: "Logician",
            group: "Analysts",
            groupCN: "分析家",
            color: "#7B8FA1",
            gradient: "linear-gradient(135deg, #7B8FA1 0%, #4A5568 100%)",
            description: "富有创造力的发明家，对知识有着无尽的渴望。喜欢理论和抽象概念。",
            strengths: ["分析能力", "创新能力", "客观理性", "独立思考"],
            weaknesses: ["忽视情感", "拖延症", "难以集中", "与社会脱节"],
            relationships: "可能在表达情感方面有困难，但重视智识上的深度交流。倾向于选择少数几个亲密朋友。",
            career: "适合需要深入研究、理论分析和创造性解决问题的领域，如研究、工程、编程、哲学等。",
            keywords: ["理性", "创新", "好奇", "独立"]
        },
        "ENTJ": {
            name: "ENTJ",
            chineseName: "指挥官",
            englishName: "Commander",
            group: "Analysts",
            groupCN: "分析家",
            color: "#E85D4C",
            gradient: "linear-gradient(135deg, #E85D4C 0%, #C0392B 100%)",
            description: "大胆、富有想象力的领导者，总是寻求改善和创新。善于制定长期战略。",
            strengths: ["领导能力", "决策果断", "自信坚定", "战略思维"],
            weaknesses: ["缺乏耐心", "过于严厉", "不易接受批评", "控制欲强"],
            relationships: "直接坦诚，可能显得强势。但对重要的人非常忠诚，愿意为关系付出努力。",
            career: "适合需要领导能力、战略规划和决策能力的领域，如企业管理、创业、政治、法律等。",
            keywords: ["领导", "果断", "自信", "战略"]
        },
        "ENTP": {
            name: "ENTP",
            chineseName: "辩论家",
            englishName: "Debater",
            group: "Analysts",
            groupCN: "分析家",
            color: "#FF8C42",
            gradient: "linear-gradient(135deg, #FF8C42 0%, #E67E22 100%)",
            description: "聪明好奇的思想者，喜欢挑战现状。善于发现问题并寻找创造性的解决方案。",
            strengths: ["创意丰富", "思维敏捷", "善于沟通", "喜欢辩论"],
            weaknesses: ["难以专注", "忽视细节", "情绪化", "喜欢争论"],
            relationships: "喜欢智识上的刺激和有趣的对话。可能在承诺方面有困难，但对朋友非常忠诚。",
            career: "适合需要创新、沟通和灵活应变能力的领域，如营销、创业、公关、咨询、发明等。",
            keywords: ["创新", "辩论", "活力", "聪明"]
        },
        "INFJ": {
            name: "INFJ",
            chineseName: "提倡者",
            englishName: "Advocate",
            group: "Diplomats",
            groupCN: "外交家",
            color: "#9B59B6",
            gradient: "linear-gradient(135deg, #9B59B6 0%, #7D3C98 100%)",
            description: "安静而富有同理心的理想主义者，有着强烈的内在价值观和对帮助他人的渴望。",
            strengths: ["同理心", "洞察力", "创造力", "坚持理想"],
            weaknesses: ["过度付出", "完美主义", "逃避冲突", "过于敏感"],
            relationships: "非常重视深度和真实性。倾向于建立少数但深厚的关系，对朋友忠诚无比。",
            career: "适合需要洞察力、同理心和创造力的领域，如心理咨询、教育、艺术、写作、社会工作等。",
            keywords: ["理想", "同理", "洞察", "创造"]
        },
        "INFP": {
            name: "INFP",
            chineseName: "调停者",
            englishName: "Mediator",
            group: "Diplomats",
            groupCN: "外交家",
            color: "#1ABC9C",
            gradient: "linear-gradient(135deg, #1ABC9C 0%, #16A085 100%)",
            description: "富有诗意、善良的梦想家，始终在寻找生命的意义和价值。",
            strengths: ["创意丰富", "同理心强", "理想主义", "忠诚"],
            weaknesses: ["不切实际", "逃避现实", "过度自我牺牲", "难以做决定"],
            relationships: "重视情感深度和精神连接。倾向于寻找灵魂伴侣，对爱情充满理想。",
            career: "适合需要创造力、同理心和自我表达的领域，如艺术、写作、音乐、心理辅导、志愿服务等。",
            keywords: ["理想", "创意", "善良", "敏感"]
        },
        "ENFJ": {
            name: "ENFJ",
            chineseName: "主人公",
            englishName: "Protagonist",
            group: "Diplomats",
            groupCN: "外交家",
            color: "#F39C12",
            gradient: "linear-gradient(135deg, #F39C12 0%, #D68910 100%)",
            description: "富有魅力的领导者，能够激励和启发他人。真诚地关心他人的成长和幸福。",
            strengths: ["领导力", "同理心", "沟通能力", "魅力十足"],
            weaknesses: ["过度操劳", "过于理想化", "难以接受批评", "忽视自己"],
            relationships: "非常重视人际关系，喜欢帮助他人成长。善于协调和激励团队。",
            career: "适合需要领导力、沟通技巧和人际关系的领域，如管理、教育、咨询、公共关系、演艺等。",
            keywords: ["领导", "激励", "关怀", "魅力"]
        },
        "ENFP": {
            name: "ENFP",
            chineseName: "竞选者",
            englishName: "Campaigner",
            group: "Diplomats",
            groupCN: "外交家",
            color: "#E74C3C",
            gradient: "linear-gradient(135deg, #E74C3C 0%, #C0392B 100%)",
            description: "热情洋溢、富有创意的社交达人，总是充满新的想法和可能性。",
            strengths: ["热情洋溢", "创意丰富", "善于激励", "适应力强"],
            weaknesses: ["难以专注", "情绪波动", "逃避困难", "过于理想化"],
            relationships: "热爱社交，善于与人建立联系。重视情感自由，可能在承诺方面有困难。",
            career: "适合需要创造力、沟通能力和热情激励的领域，如营销、艺术、创业、写作、表演等。",
            keywords: ["热情", "创意", "活力", "激励"]
        },
        "ISTJ": {
            name: "ISTJ",
            chineseName: "物流师",
            englishName: "Logistician",
            group: "Sentinels",
            groupCN: "守卫者",
            color: "#34495E",
            gradient: "linear-gradient(135deg, #34495E 0%, #2C3E50 100%)",
            description: "务实、可靠的传统主义者。重视责任和承诺，致力于维护秩序和稳定。",
            strengths: ["可靠负责", "注重细节", "有条理", "坚持不懈"],
            weaknesses: ["僵硬死板", "不善于变通", "难以接受新事物", "情感表达困难"],
            relationships: "忠诚可靠，对承诺非常重视。可能在表达情感方面较为含蓄，但内心深处非常珍视家人和朋友。",
            career: "适合需要可靠性、组织能力和注重细节的领域，如会计、金融、管理、物流、医疗等。",
            keywords: ["可靠", "负责", "传统", "务实"]
        },
        "ISFJ": {
            name: "ISFJ",
            chineseName: "守卫者",
            englishName: "Defender",
            group: "Sentinels",
            groupCN: "守卫者",
            color: "#27AE60",
            gradient: "linear-gradient(135deg, #27AE60 0%, #1E8449 100%)",
            description: "温暖、体贴的守护者。总是把别人的需求放在自己之前，默默付出。",
            strengths: ["细心体贴", "忠诚可靠", "勤奋努力", "善于照顾"],
            weaknesses: ["过度付出", "难以拒绝", "自我价值感低", "过度自责"],
            relationships: "非常重视家庭和亲密关系。愿意为所爱的人做任何事情，有时会忽略自己的需求。",
            career: "适合需要关怀、组织能力和服务精神的领域，如护理、教育、社会工作、行政管理等。",
            keywords: ["关怀", "忠诚", "服务", "细心"]
        },
        "ESTJ": {
            name: "ESTJ",
            chineseName: "总经理",
            englishName: "Executive",
            group: "Sentinels",
            groupCN: "守卫者",
            color: "#5D6D7E",
            gradient: "linear-gradient(135deg, #5D6D7E 0%, #34495E 100%)",
            description: "务实、高效的组织者。善于管理事务，确保工作按时完成并达到标准。",
            strengths: ["领导能力", "注重效率", "善于组织", "负责任"],
            weaknesses: ["过于严厉", "缺乏灵活性", "不善于情感表达", "判断性过强"],
            relationships: "直接坦诚，重视承诺和责任。可能显得强势或缺乏耐心，但内心关心家人和朋友。",
            career: "适合需要领导、组织和管理能力的领域，如企业管理、军事、法律、金融、行政等。",
            keywords: ["组织", "效率", "负责", "传统"]
        },
        "ESFJ": {
            name: "ESFJ",
            chineseName: "执政官",
            englishName: "Consul",
            group: "Sentinels",
            groupCN: "守卫者",
            color: "#F5B041",
            gradient: "linear-gradient(135deg, #F5B041 0%, #E67E22 100%)",
            description: "热情、体贴的社交达人。善于照顾他人，喜欢创造和谐愉快的氛围。",
            strengths: ["善于社交", "关怀他人", "责任感强", "务实可靠"],
            weaknesses: ["过于关注他人", "难以接受批评", "过度操劳", "害怕冲突"],
            relationships: "非常重视人际关系，喜欢为他人服务。善于组织社交活动，关心朋友和家人的需求。",
            career: "适合需要人际交往、服务精神和组织能力的领域，如教育、护理、服务业、人力资源、行政等。",
            keywords: ["关怀", "社交", "服务", "和谐"]
        },
        "ISTP": {
            name: "ISTP",
            chineseName: "鉴赏家",
            englishName: "Virtuoso",
            group: "Explorers",
            groupCN: "探险家",
            color: "#85929E",
            gradient: "linear-gradient(135deg, #85929E 0%, #5D6D7E 100%)",
            description: "大胆实用的动手者，善于分析问题的本质。喜欢探索事物的运作方式。",
            strengths: ["动手能力", "冷静分析", "适应力强", "务实"],
            weaknesses: ["情感封闭", "冒险精神过度", "难以承诺", "不善于表达"],
            relationships: "重视独立和自由，可能显得冷漠或疏远。但对于重要的人非常忠诚和关心。",
            career: "适合需要动手能力、分析思维和解决实际问题的领域，如工程、技术、机械、体育、艺术等。",
            keywords: ["实用", "分析", "动手", "冷静"]
        },
        "ISFP": {
            name: "ISFP",
            chineseName: "探险家",
            englishName: "Adventurer",
            group: "Explorers",
            groupCN: "探险家",
            color: "#76D7C4",
            gradient: "linear-gradient(135deg, #76D7C4 0%, #48C9B0 100%)",
            description: "富有艺术感的探险家，敏感而温柔。注重个人价值观和美学体验。",
            strengths: ["艺术天赋", "敏感细腻", "适应力强", "善于观察"],
            weaknesses: ["逃避冲突", "难以做决定", "过度自我保护", "不善于规划"],
            relationships: "重视个人空间和自由，但对于亲密关系非常忠诚和投入。倾向于用行动表达关心。",
            career: "适合需要创意、艺术感和动手能力的领域，如艺术、设计、音乐、摄影、烹饪、园艺等。",
            keywords: ["艺术", "自由", "敏感", "探索"]
        },
        "ESTP": {
            name: "ESTP",
            chineseName: "企业家",
            englishName: "Entrepreneur",
            group: "Explorers",
            groupCN: "探险家",
            color: "#E74C3C",
            gradient: "linear-gradient(135deg, #E74C3C 0%, #C0392B 100%)",
            description: "精力充沛、喜欢冒险的行动派。善于抓住机会，享受当下的刺激。",
            strengths: ["行动力强", "善于谈判", "适应力强", "魅力十足"],
            weaknesses: ["缺乏耐心", "冲动冒险", "忽视长远", "不善于规划"],
            relationships: "喜欢社交和刺激，可能在承诺方面有困难。但对朋友非常仗义和忠诚。",
            career: "适合需要行动力、谈判技巧和应变能力的领域，如销售、创业、体育、娱乐、商务等。",
            keywords: ["行动", "冒险", "活力", "现实"]
        },
        "ESFP": {
            name: "ESFP",
            chineseName: "表演者",
            englishName: "Entertainer",
            group: "Explorers",
            groupCN: "探险家",
            color: "#FF6B6B",
            gradient: "linear-gradient(135deg, #FF6B6B 0%, #EE5A5A 100%)",
            description: "热情奔放、充满活力的表演者。喜欢成为焦点，给周围带来欢乐和能量。",
            strengths: ["热情洋溢", "善于表演", "适应力强", "富有感染力"],
            weaknesses: ["难以专注", "逃避责任", "过于冲动", "害怕独处"],
            relationships: "热爱社交和聚会，喜欢成为人群中的焦点。重视当下的快乐和情感连接。",
            career: "适合需要表演、沟通和激发热情的领域，如演艺、娱乐、销售、服务业、教育等。",
            keywords: ["热情", "表演", "活力", "社交"]
        }
    }
};
